check_contrast = true

[templates]

neopywal.template = "colors_neopywal.vim"
neopywal.target = "~/.cache/wallust/colors_neopywal.vim"

fuzzel.template = "colors_fuzzel.ini"
fuzzel.target = "~/.cache/wallust/colors_fuzzel.ini"

hyprland.template = "colors_hyprland.conf"
hyprland.target = "~/.cache/wallust/colors_hyprland.ini"

macchina.template = 'colors_macchina.toml'
macchina.target = '~/.cache/wallust/colors_macchina.toml'

ags.template = "colors_ags.css"
ags.target = '~/.config/ags/colors_ags.css'

foot.template = "colors_foot.ini"
foot.target = "~/.cache/wallust/colors_foot.ini"

pywalfox.template = "colors_pywalfox.json"
pywalfox.target = "~/.cache/wal/colors.json"
